// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v0.0.2
// - protoc            v3.21.12
// source: api/article/auth.proto

package article

import (
	gin "github.com/gin-gonic/gin"
	api "github.com/sunmi-OS/gocore/v2/api"
)

// AuthServiceHTTPServer is the server API for AuthService service.
type AuthServiceHTTPServer interface {
	Push(*api.Context, *PushReq) (*PushReply, error)
}

func RegisterAuthServiceHTTPServer(s *gin.Engine, srv AuthServiceHTTPServer) {
	r := s.Group("/")
	r.POST("/private/push", _AuthService_Push_HTTP_Handler(srv))
}

func _AuthService_Push_HTTP_Handler(srv AuthServiceHTTPServer) func(g *gin.Context) {
	return func(g *gin.Context) {
		req := &PushReq{}
		ctx := api.NewContext(g)
		err := ctx.ShouldBindJSON(req)
		err = checkValidate(err)
		if err != nil {
			setRetJSON(&ctx, nil, err)
			return
		}
		resp, err := srv.Push(&ctx, req)
		setRetJSON(&ctx, resp, err)
	}
}
