// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v0.0.2
// - protoc            v3.21.12
// source: api/article/auth.proto

package article

import (
	sonic "github.com/bytedance/sonic"
)

func (m *PushReq) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *PushReq) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *PushReq) Unmarshal(buf []byte) error {
	m = new(PushReq)
	err := sonic.Unmarshal(buf, m)
	return err
}

func (m *PushReq) UnmarshalString(str string) error {
	m = new(PushReq)
	err := sonic.UnmarshalString(str, m)
	return err
}

func (m *PushReply) Marshal() ([]byte, error) {
	return sonic.Marshal(m)
}

func (m *PushReply) MarshalString() (string, error) {
	return sonic.MarshalString(m)
}

func (m *PushReply) Unmarshal(buf []byte) error {
	m = new(PushReply)
	err := sonic.Unmarshal(buf, m)
	return err
}

func (m *PushReply) UnmarshalString(str string) error {
	m = new(PushReply)
	err := sonic.UnmarshalString(str, m)
	return err
}
