// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/auth.proto

package article

import (
	_ "github.com/golang/protobuf/ptypes/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// 这个是PushReq的标题2
type PushReq struct {
	// name上面的备注
	Name      string `json:"name" binding:"required"`
	PageCount int64  `json:"page_count" binding:"required"`
	DataCount int32  `json:"data_count,omitempty"`
}

// 上面的备注1
// 上面的备注2
// 上面的备注3
type PushReply struct {
	SdkUrlUuid string `json:"sdk_url_uuid,omitempty"` // 后面的备注
}

type RealResp struct {
	Data    interface{} `json:"data,omitempty"`
	Code    int32       `json:"code,omitempty"`
	Message string      `json:"message,omitempty"`
}

type UploadOssdk3RdReq struct {
	Operator   string `json:"operator,omitempty"`
	SdkUrlUuid string `json:"sdk_url_uuid,omitempty"`
	SdkOs      string `json:"sdk_os,omitempty"`
	FileName   string `json:"file_name,omitempty"`
}

type GetOneArticlePureReq struct {
}

type GetOneArticlePureResp struct {
	Code    int64                `json:"Code,omitempty"`
	Message string               `json:"Message,omitempty"`
	Data    []*UploadOssdk3RdReq `json:"Data,omitempty"`
}
