// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/article.proto

package article

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetArticlesReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetArticlesReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticlesReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetArticlesReqMultiError,
// or nil if none found.
func (m *GetArticlesReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticlesReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	if m.GetPage() >= 999 {
		err := GetArticlesReqValidationError{
			field:  "Page",
			reason: "value must be less than 999",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PageSize

	// no validation rules for AuthorId

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = GetArticlesReqValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetName()) > 256 {
		err := GetArticlesReqValidationError{
			field:  "Name",
			reason: "value length must be at most 256 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_GetArticlesReq_Name_Pattern.MatchString(m.GetName()) {
		err := GetArticlesReqValidationError{
			field:  "Name",
			reason: "value does not match regex pattern \"^[^[0-9]A-Za-z]+( [^[0-9]A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetHome() == nil {
		err := GetArticlesReqValidationError{
			field:  "Home",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHome()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetArticlesReqValidationError{
					field:  "Home",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetArticlesReqValidationError{
					field:  "Home",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHome()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetArticlesReqValidationError{
				field:  "Home",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetArticlesReqMultiError(errors)
	}

	return nil
}

func (m *GetArticlesReq) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *GetArticlesReq) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// GetArticlesReqMultiError is an error wrapping multiple validation errors
// returned by GetArticlesReq.ValidateAll() if the designated constraints
// aren't met.
type GetArticlesReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticlesReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticlesReqMultiError) AllErrors() []error { return m }

// GetArticlesReqValidationError is the validation error returned by
// GetArticlesReq.Validate if the designated constraints aren't met.
type GetArticlesReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticlesReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticlesReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticlesReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticlesReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticlesReqValidationError) ErrorName() string { return "GetArticlesReqValidationError" }

// Error satisfies the builtin error interface
func (e GetArticlesReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticlesReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticlesReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticlesReqValidationError{}

var _GetArticlesReq_Name_Pattern = regexp.MustCompile("^[^[0-9]A-Za-z]+( [^[0-9]A-Za-z]+)*$")

// Validate checks the field values on GetArticlesReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetArticlesReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticlesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticlesReplyMultiError, or nil if none found.
func (m *GetArticlesReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticlesReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetArticles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetArticlesReplyValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetArticlesReplyValidationError{
						field:  fmt.Sprintf("Articles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetArticlesReplyValidationError{
					field:  fmt.Sprintf("Articles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetArticlesReplyMultiError(errors)
	}

	return nil
}

// GetArticlesReplyMultiError is an error wrapping multiple validation errors
// returned by GetArticlesReply.ValidateAll() if the designated constraints
// aren't met.
type GetArticlesReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticlesReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticlesReplyMultiError) AllErrors() []error { return m }

// GetArticlesReplyValidationError is the validation error returned by
// GetArticlesReply.Validate if the designated constraints aren't met.
type GetArticlesReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticlesReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticlesReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticlesReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticlesReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticlesReplyValidationError) ErrorName() string { return "GetArticlesReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetArticlesReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticlesReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticlesReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticlesReplyValidationError{}

// Validate checks the field values on Article with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Article) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Article with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ArticleMultiError, or nil if none found.
func (m *Article) ValidateAll() error {
	return m.validate(true)
}

func (m *Article) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for AuthorId

	if len(errors) > 0 {
		return ArticleMultiError(errors)
	}

	return nil
}

// ArticleMultiError is an error wrapping multiple validation errors returned
// by Article.ValidateAll() if the designated constraints aren't met.
type ArticleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleMultiError) AllErrors() []error { return m }

// ArticleValidationError is the validation error returned by Article.Validate
// if the designated constraints aren't met.
type ArticleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleValidationError) ErrorName() string { return "ArticleValidationError" }

// Error satisfies the builtin error interface
func (e ArticleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticle.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleValidationError{}

// Validate checks the field values on GetArticlesReq_Location with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArticlesReq_Location) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticlesReq_Location with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticlesReq_LocationMultiError, or nil if none found.
func (m *GetArticlesReq_Location) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticlesReq_Location) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetLat(); val < -90 || val > 90 {
		err := GetArticlesReq_LocationValidationError{
			field:  "Lat",
			reason: "value must be inside range [-90, 90]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetLng(); val < -180 || val > 180 {
		err := GetArticlesReq_LocationValidationError{
			field:  "Lng",
			reason: "value must be inside range [-180, 180]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetArticlesReq_LocationMultiError(errors)
	}

	return nil
}

// GetArticlesReq_LocationMultiError is an error wrapping multiple validation
// errors returned by GetArticlesReq_Location.ValidateAll() if the designated
// constraints aren't met.
type GetArticlesReq_LocationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticlesReq_LocationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticlesReq_LocationMultiError) AllErrors() []error { return m }

// GetArticlesReq_LocationValidationError is the validation error returned by
// GetArticlesReq_Location.Validate if the designated constraints aren't met.
type GetArticlesReq_LocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticlesReq_LocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticlesReq_LocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticlesReq_LocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticlesReq_LocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticlesReq_LocationValidationError) ErrorName() string {
	return "GetArticlesReq_LocationValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticlesReq_LocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticlesReq_Location.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticlesReq_LocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticlesReq_LocationValidationError{}
