// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v0.0.1
// - protoc            v3.21.12
// source: proto/article.proto

package article

import (
	api "github.com/sunmi-OS/gocore/v2/api"
	http_request "github.com/sunmi-OS/gocore/v2/utils/http-request"
)

// BlogServiceHTTPClient is the client API for BlogService service.
type BlogServiceHTTPClient interface {
	GetArticles(*api.Context, *GetArticlesReq) (*GetArticlesReply, error)
	CreateArticle(*api.Context, *Article) (*Article, error)
}

type BlogServiceHTTPClientImpl struct {
	hh *http_request.HttpClient
}

func NewBlogServiceHTTPClient(hh *http_request.HttpClient) BlogServiceHTTPClient {
	return &BlogServiceHTTPClientImpl{hh: hh}
}

func (c *BlogServiceHTTPClientImpl) GetArticles(ctx *api.Context, req *GetArticlesReq) (*GetArticlesReply, error) {
	resp := &GetArticlesReply{}
	_, err := c.hh.Client.R().SetContext(ctx).SetBody(req).SetResult(resp).Post("/v1/articles")
	return resp, err
}

func (c *BlogServiceHTTPClientImpl) CreateArticle(ctx *api.Context, req *Article) (*Article, error) {
	resp := &Article{}
	_, err := c.hh.Client.R().SetContext(ctx).SetBody(req).SetResult(resp).Post("/v1/author/:author_id/articles")
	return resp, err
}
